export default {
    about: {
        image1: `././images/about-logo.webp`,
        title1: `el logo`,
        details1: `Un amigo mío empezó a llamarme <i>Doctor Tattoo</i>. Quizá empezó a llamarme así porque constantemente pienso en cosas que pueden traer progreso, avances y soluciones para cualquier problema ambiental. De ahí viene el apodo, que ha evolucionado hasta convertirse en un nombre de marca que refleja fielmente mi personalidad.<br><br>La letra <mark>T</mark> en el logo representa mi apodo, así como los símbolos de los 4 elementos naturales principales — refiriéndose así a los atributos principales de mis ideas.`,
        image2: `././images/about02.webp`,
        title2: `primeros años`,
        details2: `No puedo decir que me interesara en lo que hago ahora desde que era niño. No me interesaba, pero ya tenía talento para ello.<br>Fui un niño muy normal. Ya dejé mi costumbre de comer todo en el jardín de infancia. ¡Ni siquiera los Legos y las bolas de cristal! Cuando entré en la escuela, podría haber venido el sentimiento de 'odio todo'. Aun así, mis padres lo evitaron y me llevaron al campo desde temprano para que pudiera liberar mi exceso de energía y ser al menos un poco más manejable según sus expectativas. Podría haber sido un deportista talentoso...<br>Pero mi talento comenzó como explotación y no como desarrollo consciente: las lesiones continuaron y resultó imposible seguir con mi carrera profesional.<br><br>Así, la toma de conciencia y la decepción me llevaron por otros caminos de autorrealización.<br>El skateboard podría haberme ido mejor que correr, pero me gustaba el graffiti en los parques, así que me hice amigo de sus creadores. Pasé mucho tiempo junto a las superficies — legales o no, no importaba. Pero sabía: 'No puedo hacer esto para siempre.' Necesito dar un paso más...`,
        image3: `././images/about03.webp`,
        title3: `años profesionales`,
        details3: `Entré en el mundo de la publicidad totalmente por accidente — pero cuando sucedió, se convirtió en una parte integral de mi vida. Ha sido mi trabajo, mi profesión y, en ocasiones, incluso mi forma de recreación. Dicho esto, no afirmo que sea lo único que he hecho. En ese entorno, convertir ese camino en una carrera de por vida siempre ha sido más un ideal que una situación realista.<br><br>Mi primer trabajo en una agencia de publicidad se sentía más como trabajar en una fábrica — caracterizado por tareas monumentales pero repetitivas. Aun así, la experiencia no fue inútil. Desarrollé una comprensión profunda del software, los flujos de trabajo y los procesos de producción. Sin embargo, el entorno ofrecía poco espacio para la expresión creativa real, lo que me llevó a buscar nuevos desafíos.<br><br>Eventualmente me uní a una empresa más pequeña, donde progresé rápidamente hasta el puesto de diseñador senior. Fue aquí donde por fin tuve libertad para aplicar mis ideas sin tantas limitaciones. Creé elementos de marca, gráficos personalizados, presentaciones multimedia, rotulación de vehículos — prácticamente todo dentro del ámbito del diseño creativo. Pero todo cambió después del cambio de milenio.<br></br>El fundador de la marca de ropa de moto MUGENRACE se acercó a mí para colaborar. El alcance del trabajo se extendió más allá de las fronteras y culturas, y con ello llegaron nuevos y complejos retos. Me encargaron desarrollar la identidad visual de la marca, diseñar la ropa y supervisar cada aspecto de la presencia visual de la empresa. Mis capacidades creativas encajaron bien en el papel, pero fue el desarrollo personal — formado por la exposición internacional y la diversidad cultural — lo que llenó las piezas faltantes.<br></br>Los resultados hablan por sí mismos. A lo largo de casi dos décadas, afronté cada reto con enfoque y adaptabilidad. Eventualmente, llegué a un punto de transición natural: era hora de buscar nuevos objetivos y oportunidades. El diseño gráfico y el pensamiento visual siempre serán una parte central de quien soy, pero también he dirigido mi atención a nuevas ideas que exigen el mismo nivel de creatividad, estructura y resolución de problemas. Sigo aplicando mi experiencia, disciplina y perspectiva individual allí donde me lleve el trabajo.`,
        image4: `././images/about04.webp`,
        title4: `ps...`,
        details4: `No soy de hacer ruido solo por llamar la atención — prefiero la claridad, el propósito y dejar que la calidad de mi trabajo hable por mí. Enfoco las cosas con intención y estructura, siempre buscando entregar valor mediante una ejecución reflexiva. En lugar de la autopromoción, creo en mostrar — no en decir — por eso he seleccionado una pequeña muestra de trabajos anteriores que reflejan cómo pienso y creo. Así nació la colección 'Works'.`,
    },
    content00: {
        image: `././images/works/w00_00.webp`,
        title: `WorX`,
        details: `dije SÍ...`,
    },
    content01: {
        image: `././images/works/w01_00.webp`,
        number: `01`,
        title: `LCR Racing`,
        details: `Un exitoso equipo privado de MotoGP`,
        tags: `<span>Q2 2016</span><span>global</span><span>#clothes #ideas</span>`,
        text1: `La mejor cocina de MotoGP`,
        text2: `Quienes conocen la historia del automovilismo sin duda recordarán a Lucio Cecchinello. Es el propietario de este equipo privado de MotoGP. Pasé unos años con ellos y fue un placer fantástico durante las carreras. Nuestra puerta de entrada fue la colaboración con ellos para la Copa Mundial de MotoGP.`,
        image1: `././images/works/w01_01.webp`,
        image1capt: `idea de diseño del vehículo`,
        image2: `././images/works/w01_02.webp`,
        image2capt: `detalle de diseño`,
    },
    content02: {
        image: `././images/works/w02_00.webp`,
        number: `02`,
        title: `HOME Company`,
        details: `Grupo inmobiliario húngaro`,
        tags: `<span>Q4 2019</span><span>hungría</span><span>#rebranding #portal</span>`,
        text1: `Nueva era, nuevo diseño`,
        text2: `Una compañía húngara de desarrollo inmobiliario me encargó crear una versión modernizada de su logo — una que preservara la esencia del original mientras lo adaptaba a los estándares de diseño contemporáneos. Mi enfoque fue mantener los elementos reconocibles, refinando sutilmente proporciones, tipografía y equilibrio visual para lograr una identidad fresca pero familiar. Con el tiempo, la empresa se trasladó a una nueva sede y el logo actualizado se mostró de forma prominente en diversas plataformas y ubicaciones, reforzando tanto la continuidad como la renovación en su presencia de marca.`,
        image1: `././images/works/w02_01.webp`,
        image1capt: `logo`,
        image2: `././images/works/w02_02.webp`,
        image2capt: `diseño en pared de hormigón`,
        image3: `././images/works/w02_03.webp`,
        image3capt: `logo 3D`,
    },
    content03: {
        image: `././images/works/w03_00.webp`,
        number: `03`,
        title: `Maria Herrera`,
        details: `La primera mujer que compitió en la serie MotoGP`,
        tags: `<span>Q1 2019</span><span>españa</span><span>#clothes #idea</span>`,
        text1: `Hicimos algo nuevo...`,
        text2: `Nos aventuramos en un territorio nuevo. Como la única mujer que competía en el paddock de MotoE del Campeonato Mundial de MotoGP, María Herrera aportó una mentalidad y determinación excepcionales que hicieron que el proceso de diseñar su colección de merchandising fuera particularmente interesante. El reto para mí — enfocar la creación de productos femeninos desde la perspectiva de un diseñador masculino — requirió adaptabilidad y atención a matices estéticos sutiles. El resultado fue recibido con su satisfacción genuina, una confirmación de que la colección reflejaba con éxito su personalidad y espíritu competitivo.`,
        image1: `././images/works/w03_01.webp`,
        image1capt: `camiseta`,
        image2: `././images/works/w03_02.webp`,
        image2capt: `camiseta`,
    },
    content04: {
        image: `././images/works/w04_00.webp`,
        number: `04`,
        title: `SEC`,
        details: `Empresa húngara de servicios oficiales`,
        tags: `<span>Q1 2020</span><span>hungría</span><span>#rebranding</span>`,
        text1: `Donde la reacción más rápida es importante.`,
        text2: `Mi tarea fue modernizar y refrescar su logo existente creando un diseño simple y contemporáneo que transmita la rapidez y fiabilidad de un servicio de electrodomésticos. El rediseño debía mantener cierta cercanía con el original, incluida la paleta de colores —una limitación aceptable. Se conservaron los contrastes fuertes para simbolizar fuerza y determinación. Simplifiqué y actualicé el diseño acorde con las expectativas de la época, y sigue siendo relevante hoy en día.`,
        image1: `././images/works/w04_01.webp`,
        image1capt: `antiguo y nuevo`,
        image2: `././images/works/w04_02.webp`,
        image2capt: `versión del logo`,
    },
    content05: {
        image: `././images/works/w05_00.webp`,
        number: `05`,
        title: `Fruit Dreams`,
        details: `Tienda delicatessen húngara`,
        tags: `<span>H2 2015</span><span>hungría</span><span>#branding #portal</span>`,
        text1: `Seleccionado para ti, recomendado para ti.`,
        text2: `Trabajar en este proyecto fue agradable y creativamente gratificante. El concepto ganador no fue mi primera idea, pero pronto identifiqué su fuerza: diseñar formas de letras que parecieran colgar como fruta madura, creando una metáfora visual fresca de productos que llegan al carrito de la compra. Además del logo, el alcance incluyó rediseñar la fachada de la tienda en línea con la nueva identidad lúdica. También me pidieron opinión y apoyo para la planificación del interior, asegurando que la experiencia del cliente fuera coherente del exterior al interior.`,
        image1: `././images/works/w05_01.webp`,
        image1capt: `logo`,
        image2: `././images/works/w05_02.webp`,
        image2capt: `lado del portal`,
    },
    content06: {
        image: `././images/works/w06_00.webp`,
        number: `06`,
        title: `MT Helmets`,
        details: `Otra colaboración desde MotoGP`,
        tags: `<span>Q3 2019</span><span>españa</span><span>#clothes</span>`,
        text1: `De fabricante a fabricante.`,
        text2: `A través de una colaboración profesional con un patrocinador con base en MotoGP, establecieron contacto con nosotros. Este compromiso llevó al diseño y desarrollo de prendas específicamente adaptadas para sus empleados — prendas que equilibraban funcionalidad, coherencia de marca e impacto visual, asegurando que se alinearan perfectamente con la identidad y necesidades operativas de la empresa.`,
        image1: `././images/works/w06_01.webp`,
        image1capt: `camiseta`,
        image2: `././images/works/w06_02.webp`,
        image2capt: `sudadera`,
    },
    content07: {
        image: `././images/works/w07_00.webp`,
        number: `07`,
        title: `Jasmine Cain`,
        details: `Cantante de rock estadounidense`,
        tags: `<span>H1 2015</span><span>ee.uu.</span><span>#clothes #idea #illustration</span>`,
        text1: `Érase una vez, mucho más allá de los grandes mares, en una tierra que ningún mapa podía mostrar…`,
        text2: `Trabajar en productos de ropa únicos y limitados para el mercado estadounidense, Legend's Motor Clothes, me llevó a conocer artistas y performers del mundo del motor, como la cantante y bajista Jasmine Cain.`,
        image1: `././images/works/w07_01.webp`,
        image1capt: `chaqueta de cuero`,
        image2: `././images/works/w07_02.webp`,
        image2capt: `chaqueta de cuero`,
        image3: `././images/works/w07_03.webp`,
        image3capt: `diseño del forro`,
    },
    content08: {
        image: `././images/works/w08_00.webp`,
        number: `08`,
        title: `Ilustraciones`,
        details: `Algunas de mis ilustraciones en un ramo`,
        tags: `<span>desde el principio</span><span>global</span><span>#clothes #idea #illustration</span>`,
        text1: `De vuelta al futuro...`,
        text2: `Crear ilustraciones humorísticas y entretenidas ofrece un bienvenido escape a las limitaciones de encargos rutinarios y muy específicos. Evoca recuerdos de mi adolescencia, cuando las imágenes en mi mente se materializaban en color vivo en paredes públicas y fachadas de fábricas abandonadas. Hoy en día, equipos amateurs, competidores y organizaciones deportivas suelen acercarse a mí para diseñar mascotas, anuncios divertidos, así como ropa y equipaciones.<br>Hay una satisfacción particular al ver el producto final provocar sonrisas, risas y aprecio genuino — un recordatorio de que incluso en un proceso creativo disciplinado, la alegría puede ser un resultado igual de importante.`,
        image1: `././images/works/w08_01.webp`,
        image1capt: `logo de equipo amateur de hockey sobre hielo`,
        image2: `././images/works/w08_02.webp`,
        image2capt: `equipación de hockey sobre hielo`,
        image3: `././images/works/w08_03.webp`,
        image3capt: `figura de squash team`,
        image4: `././images/works/w08_04.webp`,
        image4capt: `logo de equipo de hockey sobre hielo`,
        image5: `././images/works/w08_05.webp`,
        image5capt: `equipación de hockey sobre hielo`,
        image6: `././images/works/w08_06.webp`,
        image6capt: `ilustración para Rossi Moor`,
        image7: `././images/works/w08_07.webp`,
        image7capt: `sudadera para Rossi Moor`,
        image8: `././images/works/w08_08.webp`,
        image8capt: `camiseta para Rossi Moor`,
    },
    content09: {
        image: `././images/works/w09_00.webp`,
        number: `09`,
        title: `Giro d'Italia`,
        details: `Grande Partenza Budapest`,
        tags: `<span>Q4 2019</span><span>hungría</span><span>#clothes #idea #illustration</span>`,
        text1: `Un sueño hecho realidad...`,
        text2: `Como aficionado al ciclismo, consideré un verdadero honor diseñar una colección de edición limitada para los principales patrocinadores húngaros de la Grande Partenza del Giro d'Italia en Budapest. Desarrollé múltiples variantes para diferentes patrocinadores, siempre guiado por un principio consistente: la paleta de colores debía ser fiel tanto a la identidad del organizador del evento como a la del patrocinador. Aunque las ilustraciones incorporaban ciertos clichés inevitables asociados al evento, el resultado final fue aprobado por el cliente. El titular de los derechos del Giro d'Italia avaló formalmente los diseños;<br>sin embargo, el evento se pospuso finalmente debido a circunstancias de salud pública.`,
        image1: `././images/works/w09_01.webp`,
        image1capt: `ilustración`,
        image2: `././images/works/w09_02.webp`,
        image2capt: `camisetas`,
        image3: `././images/works/w09_03.webp`,
        image3capt: `sudaderas`,
        image4: `././images/works/w09_04.webp`,
        image4capt: `detalle de diseño`,
    },
    content10: {
        image: `././images/works/w10_00.webp`,
        number: `10`,
        title: `Grill'n'Beer`,
        details: `Streetfood / restaurante`,
        tags: `<span>Q4 2018</span><span>hungría</span><span>#branding #idea #portal</span>`,
        text1: `Historia interminable`,
        text2: `Este fue probablemente uno de mis proyectos más difíciles. El propietario del restaurante no estaba seguro de lo que quería ni de lo que le gustaba. Hubo muchas reuniones personales, visitas al local, planificación y bocetos, así que tardó en llegarse al resultado final. Desgraciadamente, la pandemia llegó poco después y el proyecto no pudo completarse.`,
        image1: `././images/works/w10_01.webp`,
        image1capt: `versiones del logo`,
        image2: `././images/works/w10_02.webp`,
        image2capt: `diseño de mesa`,
        image3: `././images/works/w10_03.webp`,
        image3capt: `fachada del portal`,
        image4: `././images/works/w10_04.webp`,
        image4capt: `ideas de interior`,
        image5: `././images/works/w10_05.webp`,
        image5capt: `ilustración para el baño`,
    },
    content11: {
        image: `././images/works/w11_00.webp`,
        number: `11`,
        title: `BOÉ Racing`,
        details: `Equipo familiar de Moto3 (de MotoGP)`,
        tags: `<span>2018_19</span><span>global</span><span>#clothes #idea</span>`,
        text1: `Necesidad de velocidad`,
        text2: `Son un equipo muy amable en la clase Moto3 (de MotoGP), y ha sido un honor trabajar con ellos durante algunos años. Disfruté trabajando con ellos, de las fiestas, e incluso diseñé monos de cuero para sus pilotos.`,
        image1: `././images/works/w11_01.webp`,
        image1capt: `diseño de mono de competición`,
        image2: `././images/works/w11_02.webp`,
        image2capt: `en el box`,
        image3: `././images/works/w11_03.webp`,
        image3capt: `Makar Yurchenko & Kazuki Masaki`,
    },
    content12: {
        image: `././images/works/w12_00.webp`,
        number: `12`,
        title: `TASCA Racing Team`,
        details: `(Antiguo) equipo italiano de Moto2 (de MotoGP)`,
        tags: `<span>2018_19</span><span>global</span><span>#clothes #idea #illustration</span>`,
        text1: `El circo nunca para...`,
        text2: `Diseñé ropa de paddock para el antiguo equipo de MotoGP, enfrentando algunas restricciones pero creando unas camisetas únicas que se hicieron muy populares.`,
        image1: `././images/works/w12_01.webp`,
        image1capt: `camiseta personalizada de paddock`,
        image2: `././images/works/w12_02.webp`,
        image2capt: `diseño personalizado`,
        image3: `././images/works/w12_03.webp`,
        image3capt: `ropa de equipo de paddock`,
        image4: `././images/works/w12_04.webp`,
        image4capt: `Mattia Pasini`,
        image5: `././images/works/w12_05.webp`,
        image5capt: `Simone Corsi`,
    },
    content13: {
        image: `././images/works/w13_00.webp`,
        number: `13`,
        title: `Tankcsapda`,
        details: `La banda de rock más famosa y popular de Hungría`,
        tags: `<span>2018_19</span><span>hungría</span><span>#clothes #idea #illustration</span>`,
        text1: `"Esta es esa casa"`,
        text2: `Durante décadas, Tankcsapda ha sido la banda de rock más prominente en la Cuenca de los Cárpatos. Compartieron sus ideas conmigo y colaboramos para crear colecciones de edición limitada inspiradas en fiestas salvajes y estilos diversos.<br><br>En nuestras reuniones mantuvimos largas conversaciones — explorando direcciones creativas potenciales, refinando conceptos y evaluando posibilidades. Compartieron insights valiosos extraídos de su experiencia en ventas y aprovisionamiento de producto. Yo destilé estas perspectivas en un concepto distintivo, diseñado para encarnar tanto su energía como nuestra visión compartida. El resultado no fue solo una colección, sino una expresión deliberada de la sinergia entre su legado y mi enfoque de diseño.`,
        image1: `././images/works/w13_01.webp`,
        image1capt: `ilustración`,
        image2: `././images/works/w13_02.webp`,
        image2capt: `ilustración`,
        image3: `././images/works/w13_03.webp`,
        image3capt: `ropa`,
        image4: `././images/works/w13_04.webp`,
        image4capt: `ropa`,
    },
    content14: {
        image: `././images/works/w14_00.webp`,
        number: `14`,
        title: `ACAT SE`,
        details: `El medio ambiente y la responsabilidad son el futuro`,
        tags: `<span>Q1 2021</span><span>méxico</span><span>#branding #idea #illustration #environmentalism</span>`,
        text1: `Con pequeños pasos hacia el futuro.`,
        text2: `Con el paso del tiempo, me volví más consciente de los problemas sociales y ambientales, y mi interés por crear soluciones prácticas y alcanzables para abordar preocupaciones globales se profundizó. Junto con un amigo, sentamos las bases de una descripción de Know-How sobre espacios de vida responsables, incorporando una amplia gama de pilares, de la A a la Z. Continuamos desarrollando y mejorando estas ideas.`,
        image1: `././images/works/w14_01.webp`,
        image1capt: `logo`,
        image2: `././images/works/w14_02.webp`,
        image2capt: `diseño web`,
        image3: `././images/works/w14_03.webp`,
        image3capt: `diseño web`,
    },
    content15: {
        image: `././images/works/w15_00.webp`,
        number: `15`,
        title: `Mugenrace`,
        details: `Empresa global de prendas para motocicletas`,
        tags: `<span>2001_21</span><span>global</span><span>#branding #clothes #ideas #illustration</span>`,
        text1: `Viviendo al límite`,
        text2: `Desde los primeros días de Mugenrace, he estado profundamente involucrado en moldear la identidad visual y creativa de la marca. Uno de los pasos iniciales fue diseñar el logo — una síntesis abstracta de significado simbólico y estética funcional. El nombre Mugen, que se traduce como "infinito" en japonés, evocó conceptos de ilimitación y resistencia. Busqué expresar esto a través de un emblema estilizado que trascendiera la forma literal: una estructura que sugiriera movimiento, fuerza y protección sin apoyarse en motivos convencionales. Esta base conceptual se reforzó una década después con la adición de un escudo, subrayando el compromiso de la marca con la durabilidad y el rendimiento.<br><br>Más allá de la identidad visual, mi participación se extendió al diseño de productos y, eventualmente, a la supervisión del proceso de producción. Abordé cada tarea con una mentalidad metódica y orientada a sistemas, asegurando que cada elemento — desde prototipos hasta productos finales — se alineara con la narrativa evolutiva de la marca.`,
        image1: `././images/works/w15_01.webp`,
        image1capt: `versiones del logo`,
        image2: `././images/works/w15_02.webp`,
        image2capt: `diseño de monos de cuero`,
        image3: `././images/works/w15_03.webp`,
        image3capt: `diseño de chaquetas de cuero`,
        image4: `././images/works/w15_04.webp`,
        image4capt: `diseño de chaquetas textiles`,
        image5: `././images/works/w15_05.webp`,
        image5capt: `material de marca`,
        image6: `././images/works/w15_06.webp`,
        image6capt: `material impreso`,
        image7: `././images/works/w15_07.webp`,
        image7capt: `ropa de equipo de competición`,
        image8: `././images/works/w15_08.webp`,
        image8capt: `diseño web`,
        image9: `././images/works/w15_09.webp`,
        image9capt: `diseño web`,
        image10: `././images/works/w15_10.webp`,
        image10capt: `maquetación web`,
        image11: `././images/works/w15_11.webp`,
        image11capt: `calcomanías para vehículos`,
        image12: `././images/works/w15_12.webp`,
        image12capt: `pilotos/equipos apoyados: Team MUGENRACE (moto3)`,
        image13: `././images/works/w15_13.webp`,
        image13capt: `pilotos/equipos apoyados: Team Snipers (moto3)`,
        image14: `././images/works/w15_14.webp`,
        image14capt: `pilotos/equipos apoyados: Efrén Vázquez (moto3)`,
        image15: `././images/works/w15_15.webp`,
        image15capt: `pilotos/equipos apoyados: Gábor Talmácsi (moto 125 & 250 / sbk)`,
    },
    content16: {
        image: `././images/works/w16_00.webp`,
        number: `16`,
        title: `Whitefish`,
        details: `Empresa húngara de logística y fulfillment`,
        tags: `<span>Q4 2021</span><span>hungría</span><span>#branding</span>`,
        text1: `En constante movimiento.`,
        text2: `El logo actúa como pilar central de la identidad visual de una empresa moderna de fulfillment y logística — diseñado alrededor de los principios de eficiencia, precisión tecnológica y la naturaleza dinámica del comercio contemporáneo. Su diseño se origina en la letra "W", referencia directa al nombre de la compañía, mientras que su forma curva y tipo cinta simboliza continuidad, procesos sin fisuras y el movimiento de mercancías desde las estanterías del almacén hasta el cliente final.<br><br>Dentro de la superficie de la cinta hay un sutil motivo de código de barras estilizado — más que un elemento decorativo, es un emblema de una de las herramientas más esenciales de la logística. La compresión y expansión gradual de sus líneas transmiten flujo de datos, trazabilidad y la omnipresencia de la tecnología de la información. El degradado de blanco a gris proyecta sofisticación metálica, reflejando la infraestructura moderna y la fiabilidad de la empresa, mientras que el fino contorno cian aporta frescura e innovación, anclando el diseño en la era digital.<br><br>El resultado es un logo atemporal y contemporáneo, que habla por igual a la confianza de los socios y al ritmo implacable del mercado digital — una manifestación visual del pensamiento orientado al futuro que sostiene la posición de la empresa en la implacable arena del fulfillment.`,
        image1: `././images/works/w16_01.webp`,
        image1capt: `versiones del logo`,
        image2: `././images/works/w16_02.webp`,
        image2capt: `calcomanías para vehículos`,
    },
    content17: {
        image: `././images/works/w17_00.webp`,
        number: `17`,
        title: `Cerebrulean`,
        details: `Ciencia en el deporte.`,
        tags: `<span>Q4 2023</span><span>españa</span><span>#branding #idea #illustration</span>`,
        text1: `A la vanguardia de la ciencia deportiva.`,
        text2: `La compañía estadounidense Cerebrulean™ me pidió crear toda su identidad corporativa y diseñar su presencia digital. Su misión y actividad principal es maximizar la condición física y mental de atletas profesionales usando su fórmula y procedimientos únicos, prestando especial atención a la dinámica y precisión del movimiento.<br><br>Durante el diseño me basé en los pilares básicos de la marca: movimiento y ciencia. El logo representa el contorno del centro nervioso del cuerpo incrustado en la silueta humana, en cuyas líneas intenté simbolizar la visión de la matriz de conexiones neuronales. La tecnología del sitio web mantuvo una apariencia limpia y simple que simboliza precisión. Además, traté de mover el contenido con moderación para transmitir lo esencial de la profesión del cliente. También se crearon algunas ilustraciones únicas para la web, relacionadas con el tema.<br><br><a href="https://www.cerebrulean.com" target="_blank"><mark>visitar</mark></a>`,
        image1: `././images/works/w17_01.webp`,
        image1capt: `versiones del logo`,
        image2: `././images/works/w17_02.webp`,
        image2capt: `ilustración`,
        image3: `././images/works/w17_03.webp`,
        image3capt: `ilustración`,
        image4: `././images/works/w17_04.webp`,
        image4capt: `ilustración`,
        image5: `././images/works/w17_05.webp`,
        image5capt: `diseño web`,
    },
};
